IF !DEF(GRAPHICS_INC)
DEF GRAPHICS_INC EQU 1

; we have to store the colors BACKWARDS
; so that we can read them into the BGCP in
; a nice easy way

DEF LIGHT_GREEN EQU $23f3 ; $23ee ; $136a
DEF MID_GREEN EQU $02c8 ; $034c ; $02e9 ; $0265
DEF DARK_GREEN EQU $0120
DEF OCEAN_BLUE EQU $7e29 ; $75c1 ; $7AAC
DEF WAVES_BLUE EQU $7e24
DEF WHITE EQU $7fff
DEF BLACK EQU $0000
DEF LIGHT_GRAY EQU $39ce
DEF DARK_GRAY EQU $2529
DEF BRIDGE_BROWN EQU $0552
DEF YELLOW EQU $03FF
DEF DIRT_ROAD EQU $2230
DEF WOOD_SIGN EQU $0130
DEF SKINNY_TREE EQU $0271
DEF DIRT_FLOOR EQU $00F2

DEF GRASS_GREEN EQU LIGHT_GREEN
DEF YELLOW_FLOWER EQU YELLOW
DEF BLUE_BG_COLOR EQU OCEAN_BLUE
DEF TALL_GRASS EQU MID_GREEN
DEF HEALTHY_TREE EQU DARK_GREEN
DEF STONE_WALL EQU $18C6
DEF STONE_WALL_BRICK EQU $294A

SECTION "TileDataUtils", ROM0

/** 256 tiles, each 8x8 1bpp = 8 bytes */
SECTION "TileData", ROM0, ALIGN[8]

TileData:

DEF UNUSED_TILE EQU 0
DEF RESERVED EQU 0
DEF END_OF_TILESET EQU $FF

; 16 tiles
OverworldTiles:
; the start address of the tile
RSRESET
DEF EMPTY_TILE RB $8
DEF FLOWER_TILE RB $8
DEF GRASS_TILE RB $8
DEF ROAD_TILE RB $8
DEF SIGN_TILE RB $8
DEF TREE_ONE_TILE RB $8
DEF TREE_TWO_TILE RB $8
DEF WALL_TILE RB $8
DEF WATER_TILE RB $8
DEF WATER_EDGE_TILE RB $8
DEF BRIDGE_TILE RB $8
DEF CLIFF_TILE RB $8
DEF CLIFF_EDGE_TILE RB $8
DEF CAVE_TILE RB $8
DEF _UNUSED_1 RB $8
DEF DOOR_TILE RB $8

INCBIN "assets/prototype/house-1bpp-no-grid-bw.1bpp"
OverworldTilesEnd:

PlayerSprite:
  db $FF, $FF, $FF, $FF
  db $FF, $FF, $FF, $FF
  db $FF, $FF, $FF, $FF
  db $FF, $FF, $FF, $FF
PlayerSpriteEnd:

ENDC