IF !DEF(TEST_MAP_INC)
DEF TEST_MAP_INC EQU 1

Section "House1bppNoGridBwY0X0Map", ROM0

Start: ; marks the "initial map"
House1bppNoGridBwY0X0Map:
  db HIGH(House1bppNoGridBwY0X0MapTileset), LOW(House1bppNoGridBwY0X0MapTileset), 
  db HIGH(House1bppNoGridBwY0X0MapTilesetMetadata), LOW(House1bppNoGridBwY0X0MapTilesetMetadata), 
  db HIGH(House1bppNoGridBwY0X0MapDMGBGPalettes), LOW(House1bppNoGridBwY0X0MapDMGBGPalettes), 
House1bppNoGridBwY0X0MapData:
; this file will be generated
INCLUDE "maps/house-1bpp-no-grid-bw-y0-x0-data.inc"

House1bppNoGridBwY0X0MapTileset:
db EMPTY_TILE, FLOWER_TILE, GRASS_TILE, ROAD_TILE, SIGN_TILE, TREE_ONE_TILE, TREE_TWO_TILE, WALL_TILE
db WATER_TILE, WATER_EDGE_TILE, BRIDGE_TILE, CLIFF_TILE, CLIFF_EDGE_TILE, CAVE_TILE, UNUSED_TILE , DOOR_TILE, END_OF_TILESET

House1bppNoGridBwY0X0MapTilesetMetadata:
db PASSABLE_TILE, PASSABLE_TILE, PASSABLE_TILE, PASSABLE_TILE, BLOCKING_TILE, BLOCKING_TILE, BLOCKING_TILE, BLOCKING_TILE
db BLOCKING_TILE, BLOCKING_TILE, PASSABLE_TILE, BLOCKING_TILE, BLANK_TILE, PASSABLE_TILE, BLOCKING_TILE , PASSABLE_TILE, END_OF_TILESET

; specifies one pair of colors per tile
; the low value, and the high value
; 2 pairs are read into each of 8 palettes
; so we have 16 distinct color pairs
; the "low" color and the "high" color
House1bppNoGridBwY0X0MapDMGBGPalettes:
dw TALL_GRASS, TALL_GRASS
dw TALL_GRASS, YELLOW_FLOWER
dw TALL_GRASS, GRASS_GREEN
dw TALL_GRASS, SKINNY_TREE
dw TALL_GRASS, WOOD_SIGN
dw TALL_GRASS, HEALTHY_TREE
dw TALL_GRASS, DIRT_ROAD
dw STONE_WALL, STONE_WALL_BRICK

dw OCEAN_BLUE, OCEAN_BLUE
dw DIRT_FLOOR, OCEAN_BLUE
dw OCEAN_BLUE, BRIDGE_BROWN
dw STONE_WALL_BRICK, DIRT_FLOOR
dw TALL_GRASS, DIRT_FLOOR
dw STONE_WALL_BRICK, BLACK
dw BLACK, BLACK
dw STONE_WALL, DIRT_FLOOR


ENDC
